on: [push, pull_request]

name: Codecov

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v1

    - name: Install Packages
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          antlr3 \
          ccache \
          cmake \
          cxxtest \
          gcovr \
          lcov \
          libantlr3c-dev \
          libcln-dev \
          libgmp-dev

    - name: Restore Dependencies
      id: restore-deps
      uses: actions/cache@v1
      with:
        path: deps
        key: ${{ runner.os }}-deps-symfpu-cadical-cms-lfsc-${{ hashFiles('contrib/get-**.sh') }}

    - name: Setup Dependencies
      if: steps.restore-deps.outputs.cache-hit != 'true'
      run: |
        ./contrib/get-symfpu
        ./contrib/get-cadical
        ./contrib/get-cryptominisat
        ./contrib/get-lfsc-checker

    - name: Configure
      run: ./configure.sh debug --coverage --lfsc --symfpu --cadical --cryptominisat

    - name: Build
      run: make -j2
      working-directory: build

    - name: Run CTest
      run: ctest -j2 --output-on-failure -L regress0
      working-directory: build

    - name: Collect coverage information
      run: lcov --capture --directory build --output-file lcov.txt

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v1
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        file: ./lcov.txt
        fail_ci_if_error: true

#    - name: Coveralls
#      uses: coverallsapp/github-action@master
#      with:
#        path-to-lcov: lcov.info
#        github-token: ${{ secrets.COVERALLS_TOKEN }}
