name: Update Copyright Headers

on: [pull_request, pull_request_target]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}

      - uses: jitterbit/get-changed-files@v1
        run: |
          contrib/update-copyright.pl ${{ steps.files.outputs.all }}

      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: 'Update copyright headers for modified files.'

