name: Update Copyright Headers

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}

      - name: Update headers
        run: ./contrib/ci-update-headers.sh

      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: 'Update copyright headers for modified files.'

